version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_covid_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid
    outputs:
      highly_sensitive:
        cohort: output/input_covid.csv

  generate_covid_community_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_community
    outputs:
      highly_sensitive:
        cohort: output/input_covid_community.csv

  generate_pneumonia_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pneumonia
    outputs:
      highly_sensitive:
        cohort: output/input_pneumonia.csv
  
  matching_pneumonia:
    run: python:latest python analysis/match_running.py "input_pneumonia"
    needs: [generate_covid_cohort, generate_pneumonia_cohort]
    outputs:
      moderately_sensitive:
        matching_report: output/matching_report_control_pneumonia.txt
      highly_sensitive:
        combined: output/matched_combined_control_pneumonia.csv

  matching_data_management:
    run: stata-mp:latest analysis/300_cr_data_management_matching.do 
    needs: [generate_covid_cohort, generate_pneumonia_cohort]
    outputs:
      highly_sensitive:
        combined3: output/matched_combined_pneumonia.dta
