version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_cohorts:
    run: cohortextractor:latest generate_cohort
    outputs:
      highly_sensitive:
        covid_cohort: output/input_covid.csv
        pneumonia_cohort: output/input_pneumonia.csv
        ctrl_2019_cohort: output/input_control_2019.csv
        ctrl_2020_cohort: output/input_control_2020.csv

