version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_covid_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid
    outputs:
      highly_sensitive:
        cohort: output/input_covid.csv

  generate_covid_community_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_community
    outputs:
      highly_sensitive:
        cohort: output/input_covid_community.csv

  generate_pneumonia_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pneumonia
    outputs:
      highly_sensitive:
        cohort: output/input_pneumonia.csv


  crmain:
    run: stata-mp:latest analysis/01_t1dm_cr_analysis_dataset.do
    needs: [generate_cohorts]
    outputs:
      highly_sensitive:
        analysis_dataset: output/analysis_dataset.dta
        analysis_dataset_formatching: output/analysis_dataset_formatching.dta
        analysis_dataset_formatching10PercentSample: output/analysis_dataset_formatchingTENPERCENT.dta
        cases_2020: output/input_covid.csv
        controls_2020: output/input_controls_2020.csv
      moderately_sensitive:
        log: released_analysis_results/01_t1dm_cr_create_analysis_dataset.log



  python_matching_2020:
    run: python:latest python analysis/match_running.py "control_2020"
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        matching_report: output/matching_report_control_2020.txt
      highly_sensitive:
        combined: output/matched_combined_control_2020.csv



