version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_cohorts:
    run: cohortextractor:latest generate_cohort
    outputs:
      highly_sensitive:
        cohort: output/input.csv

